apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment1
  labels:
    app: nginx
    ver: v1
spec:
  replicas: 5
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
      ver: v1
  template:
    metadata:
      labels:
        app: nginx
        ver: v1
    spec:
      containers:
      - name: nginx
        image: vergeops/versioned-nginx:1.0
